---
 - name: Install filebeat and transfer configuration file to VMs
   hosts: webservers
   become: true
   tasks:

    - name: Download deb file for filebeat
      command:
        cmd: curl -L -O      https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-7.6.1-amd64.deb
    - name: Install filebeat from downloaded file
      command:
        cmd: dpkg -i filebeat-7.6.1-amd64.deb

    - name: Copy filebeat config file to VM
      copy:
        src: /etc/ansible/filebeat-config.yml
        dest: /etc/filebeat/filebeat.yml

    - name: Enable filebeat system
      command:
        cmd: filebeat modules enable system

    - name: Setup filebeat
      command:
        cmd: filebeat setup

    - name: Start filebeat service
      command:
        cmd: service filebeat start

    - name: Enable filebeat on boot
      systemd:
        name: filebeat
        enabled: yes
